export const headCells = [
  {
    id: "surName",
    numeric: true,
    disablePadding: false,
    label: "Прізвище",
  },
  {
    id: "test_31",
    numeric: true,
    disablePadding: false,
    label: "31",
  },
  {
    id: "test_32",
    numeric: true,
    disablePadding: false,
    label: "32",
  },
  {
    id: "test_33",
    numeric: true,
    disablePadding: false,
    label: "33",
  },
  {
    id: "test_34",
    numeric: true,
    disablePadding: false,
    label: "34",
  },
  {
    id: "test_41",
    numeric: true,
    disablePadding: false,
    label: "41",
  },
  {
    id: "test_43",
    numeric: true,
    disablePadding: false,
    label: "43",
  },
  {
    id: "test_51",
    numeric: true,
    disablePadding: false,
    label: "51",
  },
  {
    id: "test_53",
    numeric: true,
    disablePadding: false,
    label: "53",
  },
  {
    id: "test_56",
    numeric: true,
    disablePadding: false,
    label: "56",
  },
  {
    id: "test_57",
    numeric: true,
    disablePadding: false,
    label: "57",
  },
  {
    id: "test_65",
    numeric: true,
    disablePadding: false,
    label: "65",
  },
  {
    id: "test_66",
    numeric: true,
    disablePadding: false,
    label: "66",
  },
  {
    id: "test_67",
    numeric: true,
    disablePadding: false,
    label: "67",
  },
  {
    id: "test_68",
    numeric: true,
    disablePadding: false,
    label: "68",
  },
  {
    id: "test_72",
    numeric: true,
    disablePadding: false,
    label: "72",
  },
  {
    id: "test_73",
    numeric: true,
    disablePadding: false,
    label: "73",
  },
  {
    id: "report",
    numeric: true,
    disablePadding: false,
    label: "Звіт",
  },
  {
    id: "teacher",
    numeric: true,
    disablePadding: false,
    label: "Викладач",
  },
  {
    id: "conspectus",
    numeric: true,
    disablePadding: false,
    label: "Конспект",
  },
  {
    id: "exercise",
    numeric: true,
    disablePadding: false,
    label: "Завдання",
  },
  {
    id: "rating",
    numeric: true,
    disablePadding: false,
    label: "Рейтинг",
  },
  {
    id: "exam",
    numeric: true,
    disablePadding: false,
    label: "Екзамен",
  },
];
export function createData({
  surName,
  report,
  teacher,
  conspectus,
  exercise,
  rating,
  exam,
  options,
}) {
  const {
    test_31,
    test_32,
    test_33,
    test_34,
    test_41,
    test_43,
    test_51,
    test_53,
    test_56,
    test_57,
    test_65,
    test_66,
    test_67,
    test_68,
    test_72,
    test_73,
  } = JSON.parse(options);
  return {
    surName,
    test_31,
    test_32,
    test_33,
    test_34,
    test_41,
    test_43,
    test_51,
    test_53,
    test_56,
    test_57,
    test_65,
    test_66,
    test_67,
    test_68,
    test_72,
    test_73,
    report,
    teacher,
    conspectus,
    exercise,
    rating,
    exam,
  };
}
