export const context = {
  login: "",
  password: "",
  showPassword: false,
  errorForm: false,
  errorMessage: "",
  typeUser: false,
  shwoNavigationItemDiscipline: false,
  valueNavigationItemDiscipline: "",
  openMenu: false,
  showFormDiscipline: false,
  nameDiscipline: "",
  updateDiscipline: false,
  showIconDeleteDiscipline: false,
};
