export const context = {
  login: "",
  password: "",
  showPassword: false,
  errorForm: false,
  errorMessage: "",
  typeUser: false,
  shwoNavigationItemDiscipline: false,
  valueNavigationItemDiscipline: "",
  openMenu: false,
  showFormItem: false,
  nameDiscipline: "",
  nameGroup: "",
  nameStudent: "",
  showIconDeleteItems: false,
  getGroups: false,
  showNameGroup: false,
  showSurNameStudent: false,
  disabledDiscipline: true,
  checkedRadioDiscipline: false,
  checkedRadioGroup: false,
  checkedRadioStudent: false,
};
