export default {
  signIn: "/user/authorisation",
  getDisciplines: "/discipline/get",
  addDiscipline: "/discipline/add",
  deleteDisciplines: "/discipline/delete",
  updateDiscipline: "/discipline/update",
  uploadCSV: "/discipline/upload",
  getGroups: "/group/get",
  addGroup: "/group/add",
  updateGroup: "/group/update",
  deleteGroups: "/group/delete",
  getStudents: "/student/get",
  addStudent: "/student/add",
  addListDates: "/student/add/dates",
};
